const express = require("express");
const app = express();
const NA_TEAMS = [
  {
    points: 85,
    place: 1,
    team: {
      name: "Complexity",
      id: 5005,
      logo: "https://img-cdn.hltv.org/teamlogo/R0CzydpyX02BnkAYhy3I89.svg?ixlib=java-2.1.0&s=8c5833d6069ef924fdbb2e220fefea00",
      facebook: undefined,
      twitter: "https://www.twitter.com/Complexity",
      instagram: undefined,
      country: { name: "United States", code: "US" },
      rank: 20,
      players: [
        {
          name: "floppy",
          id: 12713,
          timeOnTeam: "1 year6 months",
          mapsPlayed: 238,
          type: "Starter",
        },
        {
          name: "Grim",
          id: 13578,
          timeOnTeam: "1 year6 months",
          mapsPlayed: 238,
          type: "Starter",
        },
        {
          name: "JT",
          id: 11630,
          timeOnTeam: "1 year6 months",
          mapsPlayed: 238,
          type: "Starter",
        },
        {
          name: "hallzerk",
          id: 12840,
          timeOnTeam: "1 year",
          mapsPlayed: 150,
          type: "Starter",
        },
        {
          name: "EliGE",
          id: 8738,
          timeOnTeam: "1 month",
          mapsPlayed: 13,
          type: "Starter",
        },
        {
          name: "FaNg",
          id: 17372,
          timeOnTeam: "1 year6 months",
          mapsPlayed: 225,
          type: "Benched",
        },
        {
          id: 8447,
          name: "T.c",
          timeOnTeam: "1 year6 months",
          mapsPlayed: 238,
          type: "Coach",
        },
      ],
    },
    change: 0,
    isNew: false,
  },
  {
    points: 28,
    place: 2,
    team: {
      name: "Evil Geniuses",
      id: 10399,
      logo: "https://img-cdn.hltv.org/teamlogo/p6OXTVsTFEhOcbTJ8gmuP6.png?ixlib=java-2.1.0&w=50&s=41a619052f610fec335d17028d1f32af",
      facebook: undefined,
      twitter: "https://www.twitter.com/EvilGeniuses",
      instagram: undefined,
      country: { name: "United States", code: "US" },
      rank: 34,
      players: [
        {
          name: "autimatic",
          id: 8735,
          timeOnTeam: "1 year6 months",
          mapsPlayed: 150,
          type: "Starter",
        },
        {
          name: "HexT",
          id: 18838,
          timeOnTeam: "1 month",
          mapsPlayed: 14,
          type: "Starter",
        },
        {
          name: "Jeorge",
          id: 20333,
          timeOnTeam: "1 month",
          mapsPlayed: 14,
          type: "Starter",
        },
        {
          name: "junior",
          id: 14494,
          timeOnTeam: "1 month",
          mapsPlayed: 14,
          type: "Starter",
        },
        {
          name: "Walco",
          id: 17929,
          timeOnTeam: "1 month",
          mapsPlayed: 14,
          type: "Starter",
        },
        {
          name: "Brehze",
          id: 9136,
          timeOnTeam: "3 years10 months",
          mapsPlayed: 469,
          type: "Benched",
        },
        {
          name: "Vorborg",
          id: 21532,
          timeOnTeam: "11 months",
          mapsPlayed: 0,
          type: "Benched",
        },
        {
          id: 13176,
          name: "Axed",
          timeOnTeam: "1 month",
          mapsPlayed: 14,
          type: "Coach",
        },
      ],
    },
    change: 0,
    isNew: false,
  },
  {
    points: 22,
    place: 3,
    team: {
      name: "Nouns",
      id: 11948,
      logo: "https://img-cdn.hltv.org/teamlogo/hZai-tlfz3XBR5AAiF2w3D.png?ixlib=java-2.1.0&w=50&s=c264e2bae3dc8bac05016dcf8fb8dc72",
      facebook: undefined,
      twitter: "https://www.twitter.com/nounsesports",
      instagram: undefined,
      country: { name: "United States", code: "US" },
      rank: 38,
      players: [
        {
          name: "Bwills",
          id: 16647,
          timeOnTeam: "10 months",
          mapsPlayed: 241,
          type: "Starter",
        },
        {
          name: "nosraC",
          id: 17918,
          timeOnTeam: "9 months",
          mapsPlayed: 211,
          type: "Starter",
        },
        {
          name: "cJ",
          id: 9571,
          timeOnTeam: "7 months",
          mapsPlayed: 189,
          type: "Starter",
        },
        {
          name: "MarKE",
          id: 10892,
          timeOnTeam: "5 months",
          mapsPlayed: 137,
          type: "Starter",
        },
        {
          name: "stamina",
          id: 16893,
          timeOnTeam: "29 days",
          mapsPlayed: 5,
          type: "Starter",
        },
        {
          name: "JazzPimp",
          id: 11039,
          timeOnTeam: "9 months",
          mapsPlayed: 0,
          type: "Benched",
        },
        {
          id: 1915,
          name: "SEMPHIS",
          timeOnTeam: "10 months",
          mapsPlayed: 246,
          type: "Coach",
        },
      ],
    },
    change: 0,
    isNew: false,
  },
  {
    points: 16,
    place: 4,
    team: {
      name: "M80",
      id: 12376,
      logo: "https://img-cdn.hltv.org/teamlogo/OuizJGOOiHjkm0YsKfpzOB.png?ixlib=java-2.1.0&w=50&s=b90874c4007755144c9fce8c99d808ad",
      facebook: undefined,
      twitter: "https://www.twitter.com/i/user/1587540741756055552",
      instagram: undefined,
      country: { name: "United States", code: "US" },
      rank: 49,
      players: [
        {
          name: "malbsMd",
          id: 11617,
          timeOnTeam: "17 days",
          mapsPlayed: 12,
          type: "Starter",
        },
        {
          name: "maNkz",
          id: 15349,
          timeOnTeam: "17 days",
          mapsPlayed: 12,
          type: "Starter",
        },
        {
          name: "reck",
          id: 17378,
          timeOnTeam: "17 days",
          mapsPlayed: 12,
          type: "Starter",
        },
        {
          name: "Swisher",
          id: 16599,
          timeOnTeam: "17 days",
          mapsPlayed: 12,
          type: "Starter",
        },
        {
          name: "WolfY",
          id: 12937,
          timeOnTeam: "17 days",
          mapsPlayed: 12,
          type: "Starter",
        },
        {
          id: 7873,
          name: "dephh",
          timeOnTeam: "17 days",
          mapsPlayed: 12,
          type: "Coach",
        },
      ],
    },
    change: 1,
    isNew: false,
  },
  {
    points: 15,
    place: 5,
    team: {
      name: "Party Astronauts",
      id: 8038,
      logo: "https://img-cdn.hltv.org/teamlogo/5u8WkSr7yNWGWTNAfbEYjD.png?ixlib=java-2.1.0&w=50&s=6d1141a37578edbb5ed61cf53c28832b",
      facebook: undefined,
      twitter: "https://www.twitter.com/Partynauts_GG",
      instagram: undefined,
      country: { name: "United States", code: "US" },
      rank: 53,
      players: [
        {
          name: "ben1337",
          id: 13250,
          timeOnTeam: "3 months",
          mapsPlayed: 59,
          type: "Starter",
        },
        {
          name: "chop",
          id: 19705,
          timeOnTeam: "3 months",
          mapsPlayed: 59,
          type: "Starter",
        },
        {
          name: "PwnAlone",
          id: 15090,
          timeOnTeam: "3 months",
          mapsPlayed: 59,
          type: "Starter",
        },
        {
          name: "spek",
          id: 21723,
          timeOnTeam: "18 days",
          mapsPlayed: 7,
          type: "Starter",
        },
        {
          id: 11234,
          name: "madcow",
          timeOnTeam: "18 days",
          mapsPlayed: 7,
          type: "Coach",
        },
      ],
    },
    change: -1,
    isNew: false,
  },
  {
    points: 12,
    place: 6,
    team: {
      name: "Wildcard",
      id: 12257,
      logo: "https://img-cdn.hltv.org/teamlogo/3f9FTs1iRT7BI2GU6fVpZT.png?ixlib=java-2.1.0&w=50&s=4554afe6b2085f0ebb09a6584a5f3bbf",
      facebook: undefined,
      twitter: "https://www.twitter.com/i/user/4489315099",
      instagram: undefined,
      country: { name: "United States", code: "US" },
      rank: 61,
      players: [
        {
          name: "brett",
          id: 14799,
          timeOnTeam: "3 months",
          mapsPlayed: 56,
          type: "Starter",
        },
        {
          name: "Cryptic",
          id: 15176,
          timeOnTeam: "3 months",
          mapsPlayed: 56,
          type: "Starter",
        },
        {
          name: "freshie",
          id: 18706,
          timeOnTeam: "3 months",
          mapsPlayed: 56,
          type: "Starter",
        },
        {
          name: "SLIGHT",
          id: 19128,
          timeOnTeam: "3 months",
          mapsPlayed: 56,
          type: "Starter",
        },
        {
          name: "d4rty",
          id: 20564,
          timeOnTeam: "1 month",
          mapsPlayed: 31,
          type: "Starter",
        },
        {
          id: 11332,
          name: "horvy",
          timeOnTeam: "2 months",
          mapsPlayed: 36,
          type: "Coach",
        },
      ],
    },
    change: 0,
    isNew: false,
  },
  {
    points: 10,
    place: 7,
    team: {
      name: "ex-Snakes Den",
      id: 12310,
      logo: undefined,
      facebook: undefined,
      twitter: undefined,
      instagram: undefined,
      country: { name: "United States", code: "US" },
      rank: 69,
      players: [
        {
          name: "Cyrix",
          id: 19939,
          timeOnTeam: "2 months",
          mapsPlayed: 15,
          type: "Starter",
        },
        {
          name: "DJF",
          id: 21883,
          timeOnTeam: "2 months",
          mapsPlayed: 12,
          type: "Starter",
        },
        {
          name: "Lake",
          id: 22921,
          timeOnTeam: "2 months",
          mapsPlayed: 15,
          type: "Starter",
        },
        {
          name: "Seb",
          id: 21669,
          timeOnTeam: "2 months",
          mapsPlayed: 15,
          type: "Starter",
        },
        {
          name: "Wolffe",
          id: 17622,
          timeOnTeam: "2 months",
          mapsPlayed: 15,
          type: "Starter",
        },
      ],
    },
    change: 0,
    isNew: false,
  },
  {
    points: 8,
    place: 8,
    team: {
      name: "FLUFFY AIMERS",
      id: 12245,
      logo: "https://img-cdn.hltv.org/teamlogo/tb3tHmbkP8Ktzek07P0lIf.png?ixlib=java-2.1.0&w=50&s=c6dee26c44651e0d3876abc4d5497cb3",
      facebook: undefined,
      twitter: undefined,
      instagram: undefined,
      country: { name: "United States", code: "US" },
      rank: 80,
      players: [
        {
          name: "dea",
          id: 20692,
          timeOnTeam: "3 months",
          mapsPlayed: 41,
          type: "Starter",
        },
        {
          name: "Jason",
          id: 21120,
          timeOnTeam: "3 months",
          mapsPlayed: 41,
          type: "Starter",
        },
        {
          name: "LEARSI",
          id: 20386,
          timeOnTeam: "3 months",
          mapsPlayed: 40,
          type: "Starter",
        },
        {
          name: "Peeping",
          id: 22135,
          timeOnTeam: "3 months",
          mapsPlayed: 37,
          type: "Starter",
        },
        {
          name: "sacrifice",
          id: 21741,
          timeOnTeam: "3 months",
          mapsPlayed: 41,
          type: "Starter",
        },
      ],
    },
    change: 0,
    isNew: false,
  },
  {
    points: 7,
    place: 9,
    team: {
      name: "Rocket",
      id: 12277,
      logo: undefined,
      facebook: undefined,
      twitter: undefined,
      instagram: undefined,
      country: { name: "United States", code: "US" },
      rank: 86,
      players: [
        {
          name: "aleph",
          id: 22243,
          timeOnTeam: "2 months",
          mapsPlayed: 20,
          type: "Starter",
        },
        {
          name: "droid",
          id: 14495,
          timeOnTeam: "2 months",
          mapsPlayed: 20,
          type: "Starter",
        },
        {
          name: "Elk",
          id: 20765,
          timeOnTeam: "2 months",
          mapsPlayed: 18,
          type: "Starter",
        },
        {
          name: "nero",
          id: 15229,
          timeOnTeam: "2 months",
          mapsPlayed: 20,
          type: "Starter",
        },
        {
          name: "WOOHOO",
          id: 20620,
          timeOnTeam: "2 months",
          mapsPlayed: 18,
          type: "Starter",
        },
      ],
    },
    change: 0,
    isNew: false,
  },
  {
    points: 6,
    place: 10,
    team: {
      name: "WITHOUT WARNING",
      id: 12241,
      logo: "https://img-cdn.hltv.org/teamlogo/Ik71zYkkRWUPdpAARJpMHt.png?ixlib=java-2.1.0&w=50&s=83d120e35223852b76fb9f126acd53d3",
      facebook: undefined,
      twitter: undefined,
      instagram: undefined,
      country: { name: "United States", code: "US" },
      rank: 103,
      players: [
        {
          name: "consti",
          id: 19177,
          timeOnTeam: "3 months",
          mapsPlayed: 22,
          type: "Starter",
        },
        {
          name: "J0LZ",
          id: 17510,
          timeOnTeam: "3 months",
          mapsPlayed: 21,
          type: "Starter",
        },
        {
          name: "Pluto",
          id: 21128,
          timeOnTeam: "3 months",
          mapsPlayed: 22,
          type: "Starter",
        },
        {
          name: "Spongey",
          id: 13589,
          timeOnTeam: "3 months",
          mapsPlayed: 19,
          type: "Starter",
        },
        {
          name: "Tender",
          id: 20934,
          timeOnTeam: "3 months",
          mapsPlayed: 22,
          type: "Starter",
        },
      ],
    },
    change: 2,
    isNew: false,
  },
  {
    points: 6,
    place: 11,
    team: {
      name: "Melly Madness",
      id: 12210,
      logo: undefined,
      facebook: undefined,
      twitter: undefined,
      instagram: undefined,
      country: { name: "United States", code: "US" },
      rank: 104,
      players: [
        {
          name: "Bigantt",
          id: 23108,
          timeOnTeam: "10 days",
          mapsPlayed: 1,
          type: "Starter",
        },
        {
          name: "Friendle",
          id: 23378,
          timeOnTeam: "10 days",
          mapsPlayed: 1,
          type: "Starter",
        },
        {
          name: "jack1",
          id: 18635,
          timeOnTeam: "10 days",
          mapsPlayed: 1,
          type: "Starter",
        },
        {
          name: "JCasper",
          id: 23107,
          timeOnTeam: "10 days",
          mapsPlayed: 1,
          type: "Starter",
        },
        {
          name: "Weeza",
          id: 23109,
          timeOnTeam: "10 days",
          mapsPlayed: 1,
          type: "Starter",
        },
      ],
    },
    change: 2,
    isNew: false,
  },
  {
    points: 5,
    place: 12,
    team: {
      name: "Forsaken",
      id: 12375,
      logo: undefined,
      facebook: undefined,
      twitter: undefined,
      instagram: undefined,
      country: { name: "United States", code: "US" },
      rank: 111,
      players: [
        {
          name: "cxzi",
          id: 17353,
          timeOnTeam: "18 days",
          mapsPlayed: 7,
          type: "Starter",
        },
        {
          name: "Infinite",
          id: 14619,
          timeOnTeam: "18 days",
          mapsPlayed: 7,
          type: "Starter",
        },
        {
          name: "JBa",
          id: 21665,
          timeOnTeam: "18 days",
          mapsPlayed: 7,
          type: "Starter",
        },
        {
          name: "stanislaw",
          id: 8507,
          timeOnTeam: "18 days",
          mapsPlayed: 7,
          type: "Starter",
        },
        {
          name: "wiz",
          id: 17930,
          timeOnTeam: "18 days",
          mapsPlayed: 7,
          type: "Starter",
        },
        {
          id: 201,
          name: "Warden",
          timeOnTeam: "18 days",
          mapsPlayed: 7,
          type: "Coach",
        },
      ],
    },
    change: 2,
    isNew: false,
  },
  {
    points: 5,
    place: 13,
    team: {
      name: "PNEUMA",
      id: 12381,
      logo: undefined,
      facebook: undefined,
      twitter: undefined,
      instagram: undefined,
      country: { name: "United States", code: "US" },
      rank: 115,
      players: [
        {
          name: "4TAYLOR",
          id: 22547,
          timeOnTeam: "12 days",
          mapsPlayed: 3,
          type: "Starter",
        },
        {
          name: "dAVE",
          id: 19301,
          timeOnTeam: "12 days",
          mapsPlayed: 3,
          type: "Starter",
        },
        {
          name: "Griffin",
          id: 22400,
          timeOnTeam: "12 days",
          mapsPlayed: 1,
          type: "Starter",
        },
        {
          name: "kobruh",
          id: 16976,
          timeOnTeam: "12 days",
          mapsPlayed: 3,
          type: "Starter",
        },
        {
          name: "sam",
          id: 20784,
          timeOnTeam: "12 days",
          mapsPlayed: 3,
          type: "Starter",
        },
      ],
    },
    change: -3,
    isNew: false,
  },
  {
    points: 5,
    place: 14,
    team: {
      name: "Mythic",
      id: 5479,
      logo: "https://img-cdn.hltv.org/teamlogo/giKWRtCUgQzLqqfLUgwPvv.png?ixlib=java-2.1.0&w=50&s=1f562a9c5d9bbb7aafcedeaf233a3837",
      facebook: undefined,
      twitter: "https://www.twitter.com/MythicRebornGG",
      instagram: undefined,
      country: { name: "United States", code: "US" },
      rank: 120,
      players: [
        {
          name: "fl0m",
          id: 8503,
          timeOnTeam: "7 years",
          mapsPlayed: 719,
          type: "Starter",
        },
        {
          name: "Cooper",
          id: 15007,
          timeOnTeam: "1 year6 months",
          mapsPlayed: 147,
          type: "Starter",
        },
        {
          name: "freakazoid",
          id: 7808,
          timeOnTeam: "1 year6 months",
          mapsPlayed: 122,
          type: "Starter",
        },
        {
          name: "hate",
          id: 16163,
          timeOnTeam: "1 year6 months",
          mapsPlayed: 142,
          type: "Starter",
        },
        {
          name: "Trucklover86",
          id: 22022,
          timeOnTeam: "6 months",
          mapsPlayed: 67,
          type: "Starter",
        },
      ],
    },
    change: -3,
    isNew: false,
  },
  {
    points: 4,
    place: 15,
    team: {
      name: "ex-BHOP",
      id: 12336,
      logo: undefined,
      facebook: undefined,
      twitter: undefined,
      instagram: undefined,
      country: { name: "United States", code: "US" },
      rank: 139,
      players: [
        {
          name: "Andrew",
          id: 20573,
          timeOnTeam: "1 month",
          mapsPlayed: 2,
          type: "Starter",
        },
        {
          name: "bew",
          id: 16318,
          timeOnTeam: "1 month",
          mapsPlayed: 0,
          type: "Starter",
        },
        {
          name: "Drewtheshrew",
          id: 20513,
          timeOnTeam: "1 month",
          mapsPlayed: 1,
          type: "Starter",
        },
        {
          name: "micro",
          id: 18090,
          timeOnTeam: "1 month",
          mapsPlayed: 1,
          type: "Starter",
        },
        {
          name: "Penguin",
          id: 21241,
          timeOnTeam: "1 month",
          mapsPlayed: 1,
          type: "Starter",
        },
        {
          id: 23110,
          name: "mst",
          timeOnTeam: "1 month",
          mapsPlayed: 2,
          type: "Coach",
        },
      ],
    },
    change: 0,
    isNew: false,
  },
  {
    points: 4,
    place: 16,
    team: {
      name: "Detonate",
      id: 11336,
      logo: "https://img-cdn.hltv.org/teamlogo/lKDE1OG2CWukqAbhDtQD7k.png?ixlib=java-2.1.0&w=50&s=fd8c4b70dc33d421eb02bf8f82d241c9",
      facebook: undefined,
      twitter: "https://www.twitter.com/ggDetonate",
      instagram: "https://www.instagram.com/ggdetonate",
      country: { name: "United States", code: "US" },
      rank: 147,
      players: [
        {
          name: "Austin",
          id: 20793,
          timeOnTeam: "2 months",
          mapsPlayed: 6,
          type: "Starter",
        },
        {
          name: "Louie",
          id: 17437,
          timeOnTeam: "2 months",
          mapsPlayed: 6,
          type: "Starter",
        },
        {
          name: "mason",
          id: 23199,
          timeOnTeam: "2 months",
          mapsPlayed: 6,
          type: "Starter",
        },
        {
          name: "Pugg",
          id: 21416,
          timeOnTeam: "2 months",
          mapsPlayed: 6,
          type: "Starter",
        },
      ],
    },
    change: 7,
    isNew: false,
  },
  {
    points: 3,
    place: 17,
    team: {
      name: "Reason",
      id: 4822,
      logo: "https://img-cdn.hltv.org/teamlogo/MNnqkBZ0sI7QjUf2dXAtnN.svg?ixlib=java-2.1.0&s=2d927191151c15d9c174a536b471fdd6",
      facebook: undefined,
      twitter: "https://www.twitter.com/i/user/23521790",
      instagram: undefined,
      country: { name: "United States", code: "US" },
      rank: 160,
      players: [
        {
          name: "BeaKie",
          id: 20204,
          timeOnTeam: "26 days",
          mapsPlayed: 6,
          type: "Starter",
        },
        {
          name: "Danejoris",
          id: 15052,
          timeOnTeam: "26 days",
          mapsPlayed: 5,
          type: "Starter",
        },
        {
          name: "grape",
          id: 19707,
          timeOnTeam: "26 days",
          mapsPlayed: 6,
          type: "Starter",
        },
        {
          name: "JDubs",
          id: 20202,
          timeOnTeam: "26 days",
          mapsPlayed: 6,
          type: "Starter",
        },
        {
          name: "walker",
          id: 19174,
          timeOnTeam: "26 days",
          mapsPlayed: 6,
          type: "Starter",
        },
      ],
    },
    change: 2,
    isNew: false,
  },
  {
    points: 3,
    place: 18,
    team: {
      name: "OMiT",
      id: 12357,
      logo: "https://img-cdn.hltv.org/teamlogo/i5nkTaBo9SDGSaik1Ullta.png?ixlib=java-2.1.0&w=50&s=781fcdca25e3ed6103ae19df387258aa",
      facebook: undefined,
      twitter: "https://www.twitter.com/i/user/1402606683642384384",
      instagram: undefined,
      country: { name: "United States", code: "US" },
      rank: 162,
      players: [
        {
          name: "CoJoMo",
          id: 20629,
          timeOnTeam: "24 days",
          mapsPlayed: 4,
          type: "Starter",
        },
        {
          name: "Gabe",
          id: 20234,
          timeOnTeam: "24 days",
          mapsPlayed: 4,
          type: "Starter",
        },
        {
          name: "mds",
          id: 22267,
          timeOnTeam: "24 days",
          mapsPlayed: 4,
          type: "Starter",
        },
        {
          name: "Sandman",
          id: 22552,
          timeOnTeam: "24 days",
          mapsPlayed: 4,
          type: "Starter",
        },
        {
          name: "xaler",
          id: 21813,
          timeOnTeam: "24 days",
          mapsPlayed: 4,
          type: "Starter",
        },
      ],
    },
    change: -1,
    isNew: false,
  },
  {
    points: 3,
    place: 19,
    team: {
      name: "Limitless",
      id: 11388,
      logo: "https://img-cdn.hltv.org/teamlogo/M1NvTMcqHzhKJLSXxInuNK.png?ixlib=java-2.1.0&w=50&s=c4d1ca0618446f6360231350d574c6f0",
      facebook: undefined,
      twitter: "https://www.twitter.com/GGLimitless",
      instagram: "https://www.instagram.com/GGLimitless",
      country: { name: "United States", code: "US" },
      rank: 170,
      players: [
        {
          name: "kmrn",
          id: 20572,
          timeOnTeam: "11 months",
          mapsPlayed: 123,
          type: "Starter",
        },
        {
          name: "Makzwell",
          id: 19887,
          timeOnTeam: "11 months",
          mapsPlayed: 105,
          type: "Starter",
        },
        {
          name: "Grizz",
          id: 22069,
          timeOnTeam: "9 months",
          mapsPlayed: 93,
          type: "Starter",
        },
        {
          id: 22893,
          name: "Jeebs",
          timeOnTeam: "4 months",
          mapsPlayed: 42,
          type: "Coach",
        },
      ],
    },
    change: -1,
    isNew: false,
  },
  {
    points: 3,
    place: 20,
    team: {
      name: "Hound",
      id: 12384,
      logo: "https://img-cdn.hltv.org/teamlogo/GPLg98nBQ0Qky5NMXHwGgY.png?ixlib=java-2.1.0&w=50&s=11f38b9217e5675560f1320d497fab29",
      facebook: undefined,
      twitter: undefined,
      instagram: undefined,
      country: { name: "United States", code: "US" },
      rank: 171,
      players: [
        {
          name: "Beastman",
          id: 20788,
          timeOnTeam: "11 days",
          mapsPlayed: 3,
          type: "Starter",
        },
        {
          name: "PoseidoNN",
          id: 20787,
          timeOnTeam: "11 days",
          mapsPlayed: 3,
          type: "Starter",
        },
        {
          name: "Reason",
          id: 22169,
          timeOnTeam: "11 days",
          mapsPlayed: 3,
          type: "Starter",
        },
        {
          name: "tatm",
          id: 20786,
          timeOnTeam: "11 days",
          mapsPlayed: 3,
          type: "Starter",
        },
        {
          name: "zebra",
          id: 21400,
          timeOnTeam: "11 days",
          mapsPlayed: 3,
          type: "Starter",
        },
      ],
    },
    change: -4,
    isNew: false,
  },
  {
    points: 2,
    place: 21,
    team: {
      name: "Detonate SparX",
      id: 12189,
      logo: "https://img-cdn.hltv.org/teamlogo/T0VVS2Kisyj-QhzEnZS3ea.png?invert=true&ixlib=java-2.1.0&sat=-100&w=50&s=90b3536642bfc6f861d76e890d356acc",
      facebook: undefined,
      twitter: undefined,
      instagram: undefined,
      country: { name: "United States", code: "US" },
      rank: 191,
      players: [
        {
          name: "Andrea",
          id: 20453,
          timeOnTeam: "5 months",
          mapsPlayed: 22,
          type: "Starter",
        },
        {
          name: "Bouchard",
          id: 13326,
          timeOnTeam: "5 months",
          mapsPlayed: 22,
          type: "Starter",
        },
        {
          name: "Chowdzz",
          id: 23061,
          timeOnTeam: "5 months",
          mapsPlayed: 19,
          type: "Starter",
        },
        {
          name: "Kionetta",
          id: 21731,
          timeOnTeam: "5 months",
          mapsPlayed: 22,
          type: "Starter",
        },
        {
          name: "sapphire",
          id: 16355,
          timeOnTeam: "5 months",
          mapsPlayed: 22,
          type: "Starter",
        },
      ],
    },
    change: -1,
    isNew: false,
  },
  {
    points: 1,
    place: 22,
    team: {
      name: "Shimmer",
      id: 12190,
      logo: undefined,
      facebook: undefined,
      twitter: undefined,
      instagram: undefined,
      country: { name: "United States", code: "US" },
      rank: 201,
      players: [
        {
          name: "abby",
          id: 23060,
          timeOnTeam: "5 months",
          mapsPlayed: 31,
          type: "Starter",
        },
        {
          name: "empathy",
          id: 22302,
          timeOnTeam: "5 months",
          mapsPlayed: 31,
          type: "Starter",
        },
        {
          name: "lisa",
          id: 23059,
          timeOnTeam: "5 months",
          mapsPlayed: 31,
          type: "Starter",
        },
        {
          name: "Lx",
          id: 23058,
          timeOnTeam: "5 months",
          mapsPlayed: 31,
          type: "Starter",
        },
        {
          name: "vanessa",
          id: 22111,
          timeOnTeam: "5 months",
          mapsPlayed: 31,
          type: "Starter",
        },
      ],
    },
    change: -1,
    isNew: false,
  },
  {
    points: 1,
    place: 23,
    team: {
      name: "7AM NA",
      id: 12012,
      name: "7AM NA",
      logo: "https://img-cdn.hltv.org/teamlogo/1SiWs2F9gB2fxbiBrtj0NF.png?ixlib=java-2.1.0&w=50&s=9a84c8781e82a339f0db4c5d0ed71790",
      facebook: undefined,
      twitter: undefined,
      instagram: undefined,
      country: { name: "United States", code: "US" },
      rank: 203,
      players: [
        {
          name: "Izik",
          id: 21056,
          timeOnTeam: "8 months",
          mapsPlayed: 32,
          type: "Starter",
        },
        {
          name: "SolGoat",
          id: 17916,
          timeOnTeam: "8 months",
          mapsPlayed: 32,
          type: "Starter",
        },
        {
          name: "TiCx",
          id: 18500,
          timeOnTeam: "8 months",
          mapsPlayed: 29,
          type: "Starter",
        },
        {
          name: "Mellow",
          id: 20390,
          timeOnTeam: "6 months",
          mapsPlayed: 16,
          type: "Starter",
        },
      ],
    },
    change: -1,
    isNew: false,
  },
];

app.set("port", 3000);

app.get("/", (req, res) => {
  res.json({
    teamData: NA_TEAMS,
  });
});

app.listen(app.get("port"), () => {
  console.log("Express started on http://localhost:" + app.get("port"));
});
